# Use VLC for Video files
[opener]
play = [
    { run = 'open -a VLC "$@"', desc = "VLC", orphan = true }
]
open = [
    { run = 'open "$@"', desc = "Open", orphan = true, for = "macos" }
]
[open]
prepend_rules = [
  { mime = "video/*", use = [ "play", "reveal" ] },
]
